name: ExpenseTracker
options:
  minimumXcodeGenVersion: 2.35.0
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCT_BUNDLE_IDENTIFIER: com.expensetracker
    CODE_SIGN_STYLE: Manual
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGN_IDENTITY: ""
    DEVELOPMENT_TEAM: ""
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    INFOPLIST_FILE: ExpenseTracker/Info.plist
    CODE_SIGN_ENTITLEMENTS: ExpenseTracker/ExpenseTracker.entitlements
packages: {}
schemes:
  ExpenseTracker:
    build:
      targets:
        ExpenseTracker: all
    test:
      targets:
        - name: ExpenseTrackerTests
          parallelizable: true
          randomExecutionOrder: false
    run:
      config: Debug
    archive:
      config: Release
    profile:
      config: Release
    analyze:
      config: Debug
targets:
  ExpenseTracker:
    type: application
    platform: iOS
    sources:
      - path: ExpenseTracker
    prebuildScripts: []
    postbuildScripts: []
    settings:
      base:
        SWIFT_EMIT_LOC_STRINGS: NO
  ExpenseTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ExpenseTrackerTests
    dependencies:
      - target: ExpenseTracker
    settings:
      base:
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""