name: GenZCompanion
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
settings:
  base:
    SWIFT_VERSION: 5.9
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    CODE_SIGNING_ALLOWED: YES
packages: {}
schemes:
  GenZCompanion:
    build:
      targets:
        GenZCompanion: all
    run:
      config: Release
    test:
      config: Debug
      targets:
        - GenZCompanionTests
    archive:
      config: Release
    analyze:
      config: Debug
targets:
  GenZCompanion:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Core
      - path: Features
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.genzcompanion
        PRODUCT_NAME: GenZCompanion
        INFOPLIST_FILE: App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        TARGETED_DEVICE_FAMILY: 1
    dependencies: []
  GenZCompanionTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    settings:
      base:
        TEST_HOST: ""
        BUNDLE_LOADER: ""
    dependencies:
      - target: GenZCompanion