name: iOS Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'build-*'

jobs:
  build-ipa:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode
        shell: bash
        run: |
          xcodebuild -version
          xcodebuild -showsdks

      - name: Detect Xcode container
        shell: bash
        run: |
          set -euo pipefail
          WS=$(find . -maxdepth 3 -name "*.xcworkspace" -print -quit || true)
          PJ=$(find . -maxdepth 3 -name "*.xcodeproj"    -print -quit || true)
          if [[ -n "$WS" ]]; then
            CT="workspace"; CO="$WS"
          elif [[ -n "$PJ" ]]; then
            CT="project";   CO="$PJ"
          else
            echo "No .xcworkspace or .xcodeproj found" >&2
            exit 1
          fi
          echo "CONTAINER=$CO" >> "$GITHUB_ENV"
          echo "CONTAINER_TYPE=$CT" >> "$GITHUB_ENV"
          echo "Detected container: $CT -> $CO"

      - name: List schemes (ensure your scheme is Shared)
        shell: bash
        run: |
          if [[ "${CONTAINER_TYPE}" == "workspace" ]]; then
            xcodebuild -workspace "${CONTAINER}" -list
          else
            xcodebuild -project  "${CONTAINER}" -list
          fi

      - name: Build & Archive (no code signing)
        env:
          SCHEME: ExpenseTracker   # change if your shared scheme name differs
        shell: bash
        run: |
          set -euo pipefail
          ARCHIVE_PATH="$PWD/build/ExpenseTracker.xcarchive"
          if [[ "${CONTAINER_TYPE}" == "workspace" ]]; then
            xcodebuild \
              -workspace "${CONTAINER}" \
              -scheme "$SCHEME" \
              -configuration Release \
              -destination 'generic/platform=iOS' \
              -archivePath "$ARCHIVE_PATH" \
              archive \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              SKIP_INSTALL=NO
          else
            xcodebuild \
              -project "${CONTAINER}" \
              -scheme "$SCHEME" \
              -configuration Release \
              -destination 'generic/platform=iOS' \
              -archivePath "$ARCHIVE_PATH" \
              archive \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              SKIP_INSTALL=NO
          fi

      - name: Create unsigned IPA
        shell: bash
        run: |
          set -euo pipefail
          # Create a temporary directory for the IPA contents
          mkdir -p Payload
          
          # Find the .app in the archive
          APP_PATH=$(find "$PWD/build/ExpenseTracker.xcarchive/Products/Applications" -type d -name "*.app" -print -quit)
          if [[ -z "$APP_PATH" ]]; then
            echo "No .app found in archive" >&2
            exit 74
          fi
          
          # Copy the .app to the Payload directory
          cp -R "${APP_PATH}" Payload/
          
          # Create the IPA file
          zip -r ExpenseTracker-unsigned.ipa Payload
          
          # Clean up
          rm -rf Payload
          
          echo "Created IPA: ExpenseTracker-unsigned.ipa"
          ls -lah ExpenseTracker-unsigned.ipa

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseTracker-unsigned-ipa
          path: ExpenseTracker-unsigned.ipa
