name: iOS Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches: [ cursor/build-production-ready-expense-tracker-with-ci-dd5c ]
    tags:
      - 'build-*'

jobs:
  build-ipa:
    runs-on: macos-14  # avoid macos-latest migration blips
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode
        run: |
          xcodebuild -version
          xcodebuild -showsdks

      # Detect workspace/project (write to env, not outputs)
      - name: Detect Xcode container
        shell: bash
        run: |
          set -euo pipefail
          WS=$(find . -maxdepth 3 -name "*.xcworkspace" -print -quit || true)
          PJ=$(find . -maxdepth 3 -name "*.xcodeproj"    -print -quit || true)
          if [[ -n "$WS" ]]; then
            echo "CONTAINER=$WS" >> $GITHUB_ENV
            echo "CONTAINER_TYPE=workspace" >> $GITHUB_ENV
          elif [[ -n "$PJ" ]]; then
            echo "CONTAINER=$PJ" >> $GITHUB_ENV
            echo "CONTAINER_TYPE=project" >> $GITHUB_ENV
          else
            echo "No .xcworkspace or .xcodeproj found" >&2
            exit 1
          fi
          echo "Detected: $CONTAINER_TYPE = $CONTAINER"

      - name: List schemes (ensure your scheme is Shared)
        shell: bash
        run: |
          if [[ "${CONTAINER_TYPE}" == "workspace" ]]; then
            xcodebuild -workspace "${CONTAINER}" -list
          else
            xcodebuild -project  "${CONTAINER}" -list
          fi

      - name: Build & Archive (no code signing)
        env:
          SCHEME: ExpenseTracker   # <- change if your shared scheme differs
        shell: bash
        run: |
          set -euo pipefail
          ARCHIVE_PATH="$PWD/build/ExpenseTracker.xcarchive"
          if [[ "${CONTAINER_TYPE}" == "workspace" ]]; then
            xcodebuild \
              -workspace "${CONTAINER}" \
              -scheme "$SCHEME" \
              -configuration Release \
              -destination 'generic/platform=iOS' \
              -archivePath "$ARCHIVE_PATH" \
              archive \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              SKIP_INSTALL=NO
          else
            xcodebuild \
              -project "${CONTAINER}" \
              -scheme "$SCHEME" \
              -configuration Release \
              -destination 'generic/platform=iOS' \
              -archivePath "$ARCHIVE_PATH" \
              archive \
              CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" \
              SKIP_INSTALL=NO

      - name: Find .app
        id: find_app
        shell: bash
        run: |
          set -euo pipefail
          APP_PATH=$(find "$PWD/build/ExpenseTracker.xcarchive/Products/Applications" -type d -name "*.app" -print -quit)
          if [[ -z "$APP_PATH" ]]; then
            echo "No .app found in archive" >&2
            exit 74
          fi
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "Found app: $APP_PATH"

      - name: Create unsigned IPA
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p Payload
          cp -R "${APP_PATH}" Payload/
          zip -qry ExpenseTracker-unsigned.ipa Payload
          rm -rf Payload
          ls -lah ExpenseTracker-unsigned.ipa

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseTracker-unsigned
          path: ExpenseTracker-unsigned.ipa
