name: iOS Unsigned IPA

on:
  workflow_dispatch:
  push:
    tags:
      - 'build-*'

jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install XcodeGen (optional)
        run: |
          brew install xcodegen || true
          if [ -f project.yml ]; then xcodegen generate; fi

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -scheme ExpenseTracker -project ExpenseTracker.xcodeproj

      - name: Build (no signing)
        run: |
          xcodebuild \
            -scheme ExpenseTracker \
            -configuration Release \
            -project ExpenseTracker.xcodeproj \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            build

      - name: Archive (no signing)
        run: |
          xcodebuild \
            -scheme ExpenseTracker \
            -configuration Release \
            -project ExpenseTracker.xcodeproj \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/ExpenseTracker.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            archive

      - name: Create unsigned IPA
        run: |
          APP_PATH="$PWD/build/ExpenseTracker.xcarchive/Products/Applications/ExpenseTracker.app"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -r ExpenseTracker-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseTracker-unsigned
          path: ExpenseTracker-unsigned.ipa